### ISSUE TITLE
Job Sayfalarının eklenmesi

### ISSUE THREAD

**Issue by HarunHudaiTan** [fmgwfwt/full-stack-angular-spring#2]

**Comment by fatih-demirr** [comment]
Hi,

Thank you for your interest in this project! The purpose of this repository was to provide a working backend and frontend as a learning resource. If you want to personalize the project and add more pages, you can follow these steps:

1. **Clone the Repository**: 
   ```bash
   git clone [repository URL]
   ```

2. **Navigate to the Project Directory**:
   ```bash
   cd [repository name]
   ```

3. **Install Dependencies**:
   - For the backend (Spring Boot):
     ```bash
     ./mvnw install
     ```
   - For the frontend (Angular):
     ```bash
     cd frontend
     npm install
     ```

4. **Run the Project**:
   - For the backend:
     ```bash
     ./mvnw spring-boot:run
     ```
   - For the frontend:
     ```bash
     ng serve
     ```

5. **Add New Pages**:
   - To add new pages in Angular, you can generate components using the Angular CLI:
     ```bash
     ng generate component [component-name]
     ```
   - Update the routing module to include the new pages.

Feel free to reach out if you have any questions or run into any issues. Have fun!

Best regards,  
Fatih Demir
